---
output: pdf_document
---

Since the seminal contribution of Barry Ames on electoral connection in Brazil’s candidate-centered electoral system, a new venue on the importance of the territory for proportional representatives was open in the Political Science debate. This research takes the territorial connection of local legislators as an object of study to shed light over how territorialization strategies -- i.e., envisioning the occupation and domination of a territory -- are efficient tools in the pursue of political careers. In this path, the thesis envisions to test hypotheses that connects three independent streams of literature around the topic: electoral geography; distributive politics; and urban governance. From the incumbency advantage itself to the strategic use(s) of IBAs and the reliance on organizational brokerage mechanisms, I aim at generalizing findings that so far has been sparsely connected or in, some cases, underdeveloped, having large Brazilian municipalities as laboratories.