---
output: pdf_document
---

# Introduction {-}

## Foreword {-}

This research dissertation -- as many I guess -- was borne out of what C. Wright Mills has labelled *sociological imagination* or the capacity to “grasp history and biography and the relations between the two within society” [@mills_sociological_2000, p. 6]. As a young bureaucrat, in the late 2010s, responsible for the monitoring of individual budget amendments execution in the Secretary of Culture in the City Hall of the municipality of São Paulo, I was first confronted with the territorial logic that local legislators not rarely operate in.

I don’t remember exactly when those 55 elected representatives became familiar to me, but in between the interaction with their staff and with the recipients of their resources, I suddenly started to know by heart their names, their party affiliations, the religions that they practice, the kinds of constituencies that support them (and are supported by them) and the types of entities with whom they establish relationships, very often, associated with the places where the bulk of their votes comes from.

To be clear, by local legislators I mean what we call in Brazil by *vereadores*. In the Anglo-Saxon context, they are usually referred to as city councilors, councilperson, or yet alderperson. In other words, the elected representatives that form a legislative body associated with a city or municipality jurisdiction and that usually have as their main prerogative to promote and approve urban laws and regulations. In turn, by individual budget amendments, I mean an annual budget quota over legislators’ individual discretion usually directed to promote public works, to sponsor cultural or sports events or even to strengthen public or nonprofit programs or facilities.

It is important to say, individual budget amendments (IBAs, hereafter) are a very fetishized institution both in public and academic debate in Brazil.

In the years of 2020s, when I write these notes, it’s impossible to miss a mention about it -- or, more precisely, “budget amendments” in a wider sense -- on TV news and newspapers on a week basis. In 2022, the Brazilian Congress reached an unprecedented level of direct influence over 24% of the discretionary resources available in the federal budget in Brazil -- the double of the second country, Estonia, in a comparison with OECD countries and about ten times higher than the proportion observed in the United States, in 2019, for instance [@mendes_emendas_2023]. Although those are figures hard to ignore, it is not uncommon to see a narrative spread by the media that directly equates it to corruption, clientelism and government’s misfunctions based mostly on anecdotes. Put simply, IBAs would be the perverse quid pro quo for the legislative implementation of the government’s agenda.

This conventional wisdom, or “folkloric” comprehension of the Brazilian polity, found resonance on the first interpretations provided by political scientists about the candidate-centered electoral system adopted by the novel 1988 Constitution, disputed later. To avoid a discussion, I’ll develop in another moment, in sum, a controversy emerged in the 1990s and early 2000s around the concept of coalition presidentialism that opposed views where IBAs varied from a central institution to governability to a marginal insignificant one. Without going too much deep into each perspective, it is possible to say that the first distributivist interpretation proved inadequate during the 2000s, while the second wave of a partisan interpretation started to look like a little bit old in the late 2010s. If there was an equilibrium, it was now an unstable one. Indeed, reforms and crises changed the executive-legislative relationship along 30 years after redemocratization and no comprehensive model was developed since then -- despite incremental innovations in the literature.

I won’t forget when I first decided to speak with a senior scholar specialized in public budget in Brazil and with extensive contributions on the topic of IBAs and I mentioned that I was intending to build an original database about local legislators’ use of discretionary funds in large Brazilian municipalities. He retorted: "are there IBAs at the municipal level?” It is not surprising, though, that someone who spent a life theorizing and testing hypotheses about that same very instrument had no idea they even existed at the local level. Local politics is renegade to a minor ladder in Political Science. Notwithstanding great contributions that local politics offered to the discipline (from Nunes Leal to Dahl’s “who governs?”), researchers keep stunned by the “great” politics, mesmerized by the power games among the big shots. That is not to say that it is not interesting, but we should recognize more often that local politics is an excellent laboratory to test hypotheses. Even if we can’t lose sight of their ontological and epistemological specificities [@marques_como_2018], many building blocks of the political phenomena can be investigated there.

Nowadays, most knowledge concerning cities is dispersed in monographies and articles with fairly rich descriptions of mechanisms and some hypotheses’ testing, but usually dedicated to only one or a few case studies [@da_cruz_new_2019]. Very scarce systematic tests across multiple cases are observed. Yet, the variety of cases, in terms of institutions and geographic, economic and sociodemographic contexts, provide a fertile ground for scholars to push for the “comparative gesture” and help the discipline to move on the steps of what Schmitter [-@della_porta_design_2008] has called “the cycle of social and political research and its four logics”: discovery; explication; accuracy; and proof. Of course, this is a collective enterprise and specific object of studies and research agendas may be in distinct phases of that cycle, but I insist that the same efforts we devote to “explain” are not the same we use to seek for “accuracy” or more robust “proofs” of accumulated knowledge. This research intends to push for this movement.

Besides, there is a concentration of works in urban studies about “the great (global) cities” -- Chicago, New York, London, Paris, São Paulo, Rio de Janeiro -- that almost never encompasses what I shall call “the great ordinary cities”. It is impressive how much we can know about São Paulo and what we don’t know about Goiânia, for instance, although many of those ordinary cities are sufficiently “great” (with more than 1 million inhabitants) and have been growing in a much faster pace in proportional terms more recently^[Available in: https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37237-de-2010-a-2022-populacao-brasileira-cresce-6-5-e-chega-a-203-1-milhoes.]. Not to mention how frequent anecdotal evidence from the former are generalized as a consolidated knowledge of “local politics” at large. I aim at providing a bigger picture of the phenomenon this research is concerned about.

What is this phenomenon? Back to my young bureaucrat days, one of the first things that struck me was the regularity of places where IBAs were targeted to and how the same actors were involved in the transactions over and over again. As a middle-class young white guy, living in a wealthy neighborhood of the city of São Paulo, most of time, those were places I had never been, and the cultural producers or nonprofit organizations benefited with those resources were not the ones I had heard about. Moreover, the most prolific city councilors also were not the ones that me and my friends used to follow on social media and eventually support.

I was still an undergraduate in Social Sciences by that time, but I had already read that the Brazilian electoral system used to induce the so-called *personal vote*. The open-list proportional representation (OLPR) was the reason leading to extensive inter and intraparty competition. In fact, in the electoral arena, it seemed like if every candidate was for herself -- yet, inside parties’ and informational constraints. For instance, the median quantity of votes an elected city councilor in São Paulo receives is equivalent to 0,3% of the apt voters in that city. In absolute terms, 30 thousand in 10 million. Doing an exercise, if the municipality was to be divided in 55 electoral districts, every councilor would have to dispute a plurality, on average, of about 200 thousand voters. Imagining a majority rule, their constituencies would represent about 50 thousand (already accounting for historical absenteeism records), almost doubling the actual figures -- only six elected representatives reached that number of votes in the last elections in 2020. Not mentioning concentration yet, the system shrinks constituencies.

Moreover, the OLPR also creates a myriad of electoral strategies. Nicolau [-@nicolau_representantes_2017] lists six motivations to choose a candidate in a legislative election: personal attributes; territory; identity; ideology; interest groups; and clientelism. Although not exclusive nor exhaustive, those ideal types induce different representation “home styles”. To start with, the notion of “home” may be very distinct for a candidate that relies mostly on her personal attributes than the one that relies predominantly on her territory. Personal attributes, identity, ideology and interest groups, for instance, tend to arrange votes in a more dispersed spatial pattern than territory and clientelism, that are usually more concentrated in the space. In short, the *electoral connection* is manyfold in OLPR. Nonetheless, it is just the visible facet of what Hoyler [-@hoyler_representacao_2022] have labeled *territorial connection*, i.e., the efforts of politicians to ground their political action in the process of building their representative task.

Indeed, what I was watching almost ten years ago as a young bureaucrat was one of the ways the territorial connection is developed. Almost every politician tries to build ties with territories. Those familiarized with the legislators’ own views about their jobs know that the territory-related issues are always listed as their top priorities. Incentives coming from the electoral and the legislative arena obviously play their part, but we have devoted too little attention to understand how those resources are employed through the legislators’ point of view.

Another aspect I want to stress about my personal experience back in those days is how power and concentration seemed intertwined in my bureaucrat routines. One might imagine that city councilors are not all the same. The hierarchy of the legislative house is somehow transposed into a priority scheme in their executive demands. But, most importantly, for some legislators the process of executing the IBAs was much more flexible. “This [individual budget] amendment has to go anyway, even if we have to regularize afterwards.” It was subtle, but those exceptions were almost always associated with specific actors and specific places. In common, they shared a centrality in the executive-legislative relationship and, not rarely, they had a very concentrated behavior when targeting IBAs. Of course, it might be just a singular conjuncture that I was able to capture as an observer in a specific moment of time and space. Yet, those legislators seemed very powerful to me and those targeted places more blessed than others, as if those territories were not simply strategic in terms of electoral connection, but also as a source of political power in a governance perspective.

Finally, by introducing a governance glance in a heavily institutionalist debate, I aim at stressing some mechanisms that enables the transformation of institutional resources into actual votes. Specifically, I’m interested in the horizontal dimension of the multilevel governance framework that emphasizes the multiplication of actors and the augmented role of the third sector in policy deliverance [@kazepov_rescaling_2017]. The MROSC^[*Marco Regulatório das Organizações da Sociedade Civil* (Regulatory Framework of Civil Society Organizations).] was a law approved by the federal government in Brazil in 2014 with impacts on policy implementation at the municipal level for almost ten years now and we still know very little about those consequences. Back in my bureaucrat days, I was a witness of the rise of nonprofit organizations as beneficiaries of IBAs resources, following that more encompassing and flexible legislation. Brokerage is a fundamental piece in this puzzle in need to be further explored.

Hence, I take the territorial connection as an object of study to shed light on how it interacts with the literature concerning the use of resources at legislators’ discretion to follow what I’m calling *territorialization strategies*. From the incumbency advantage itself to the strategic use(s) of IBAs and the reliance on organizational brokerage mechanisms, I aim at generalizing findings that so far has been sparsely connected or in, some cases, underdeveloped. In terms of structure, I intend to build three independent chapters that dialogues with different facets of the phenomenon I’m concerned about, in an article-based dissertation as I present next.

## Brief research plan {-}

Since the seminal contribution of Barry Ames [-@ames_electoral_1995; -@ames_electoral_1995-1; -@ames_deadlock_2001] on electoral connection [@mayhew_congress_2004] in Brazil’s candidate-centered electoral system, a new venue on the importance of the territory for proportional representatives was open in the Political Science debate.

Although much was argued that the incentives coming from the electoral arena were not determinant inside the parliament’s doors [@figueiredo_executivo_2001] and that the hypothesis of the emergence of informal districts was most unlikely [@kinzo_padroes_2003; @avelino_concentracao_2011] authors kept finding evidences that the territory was of major importance through the eyes of the legislators [@carvalho_e_2003; @nicolau_o_2006], not rarely associated with pork and a parochialist behavior [@pereira_partidos_2003].

This seemed puzzle, indeed, reflected the combination of incentives coming from decentralized institutions in the electoral arena with centralized ones from inside the legislative house [@limongi_processo_2005]. However, the focus on the governability aspect at the federal level left overshadowed how those mechanisms were deployed at the subnational context -- especially in large municipalities -- and, most importantly, the proper investigation of how the *territorial connection* was a fundamental building block of political representation, grounding the electoral system from the local level [@hoyler_representacao_2022].

This research takes the territorial connection of local legislators as an object of study to shed light over how *territorialization strategies* [@hsing_great_2012] -- i.e., envisioning the occupation and domination of a territory -- are efficient tools in the pursue of political careers. In this path, the thesis envisions to test hypotheses that connects three independent streams of literature around the topic: electoral geography; distributive politics; and urban governance.

Chapter 1, “The concentration premium of incumbency advantage”, contributes to answer the question of: *if and which legislators seek to build territorial ties?* Diving in the electoral geography debate I aim to show that, although concentrated voting patterns are not the most usual case among legislators, it is an important one. The main hypothesis states that concentration tends to give larger returns in reelection chances, especially for those with already “concentrated” voting patterns. To test it, TSE georrefered voting data in large Brazilian municipalities is summarized in different concentration indicators (e.g., D, G) to draw a quasi-experiment based on a close-race regression discontinuity design (RDD). In turn, using unsupervised learning, the profile of “concentrated” voters will be also assessed to understand whose politician are most likely to benefit from territorialization.

Chapter 2, “The use(s) of individual budget amendments”, moves in the direction of uncovering mechanisms to foster territorialization to answer: *how discretionary funds can be used for electoral purposes?* The debate about individual budget amendments (IBAs) is a long and contested one in Political Science in Brazil. With roots on the early -- sociological and neoinstitutionalist -- interpretations of the Brazilian polity, IBAs have been recognized as a fundamental tool to governability in an executive-legislative relationship dictated by individualistic and parochialist interests. Notwithstanding how far the pork hypothesis was stretched, much less attention was devoted to understanding how IBAs were used through the legislator’s perspective. If that instrument is essentially a distributive one, pork may still be only one strategy of use of IBAs. In this way of reasoning, IBAs are usually understood as a dependent variable that tends to recompensate past electoral outcomes in a pork fashion -- i.e., contingently concentrating spatial benefits while costs are shared. However, most evidence has shown that the use of those discretionary funds follows a far more complex repertoire of strategies.

Indeed, the employment of those discretionary funds may play a manyfold function. Building on the contribution of @stokes_brokers_2013 on nonprogrammatic politics -- and its further developments by @bussell_clients_2019 --, I suggest at least three main mechanisms that the use of IBAs may fulfill: on the one hand, a *pork barrel* and a *clientelist* one; and, on the other hand, a *constituency service* alternative. Bussell’s (2019) distinction between contingent and noncontingent distribution of resources in nonprogrammatic politics is useful to highlight how IBAs can also be used to persuade constituencies. In short, instead of a partisan distribution where political support is decisive -- being it a quid pro quo for the receipt of benefits or not, i.e., clientelist or not --, the constituency service fulfills a much more strategic role focused on the conversion of nonpartisan voters. Therefore, being a potential tool towards territorialization. In this sense, the main hypothesis stands that IBAs contingent use can be as important as the contingent one, in any sense, able to be electorally instrumentalized, especially by “concentrated” legislators. To test it, econometric models, based on novel data gathered via LAI^[*Lei de Acesso à Informação* (Law of Access to Information).] requests, will be drawn having the targeting of IBAs as dependent variable and the voting patterns at the territory as the main independent one.

Chapter 3, “The microrelations of nonprofit-public partnerships”, explores one brokerage mechanism that connects representatives and their constituencies in the territory. Investigating the uses of IBAs to foment nonprofit-public partnerships (NPPPs), I help to answer: *how relevant are organizational brokers to build territorial ties?* Territorial brokers are pivotal players in this game, and they may assume different forms based on their exchange logic as intermediaries between politicians and voters. Looking specifically at *organizational brokers* [@holland_beyond_2015], I sustain the hypothesis that *community-based organizations* [@marwell_privatizing_2004] are better suited to foster territorialization strategies, even though, the network of nonprofit organizations (NPOs) encompasses a set of distinct roles that are constitutive of both the territory and citywide governance dynamics [@sampson_great_2012; @marwell_microrelations_2020]. To test it, descriptive and inferential network analysis, based on data from the Map of Civil Society Organizations^[Available in: https://mapaosc.ipea.gov.br/.] and the novel dataset on IBAs restricted to MROSC^[*Marco Regulatório das Organizações da Sociedade Civil* (Regulatory Framework of Civil Society Organizations).] partnerships, will be used to draw and extract main patterns of the network in each city studied.

One last word shall be said concerning case studies. Initially, the choice to study municipalities is because those federal entities are still underexplored in the literature around the topics this thesis is concerned about. Especially large municipalities -- let’s say, above 1 million inhabitants -- are large enough to put territories at stake. Besides, most hypotheses in this study are derived from previous work concerning the municipality of São Paulo -- an extreme case in this sense. Thus, at this moment, case selection has focused on a diverse but limited set of cases that covers at least one municipality in each region of Brazil: Manaus, Fortaleza, Goiânia, São Paulo and Curitiba. When possible, a more encompassing set of cases may be used, while, if needed, case studies will be reduced to a few exploratory units according to chapters’ constraints. The same can be said for the timeframe, initially, data on the two last legislatures -- 2016-2020 and 2020-2024 -- are being collected, but in specific chapters’ circumstances, it may be enlarged or shortened.

The research is perennially in its literature review phase. In parallel, document analyses of IBAs execution process in each municipality is being systematized, besides first LAI requests concerning IBAs execution in the last two legislatures year-by-year. In terms of methods, opportunities to rely in quasi-experiments are being studied as well as the use of qualitative evidence to strengthen causal inference of some hypotheses. In the next pages, I present the first tentative initial versions of Chapters 1, 2 and 3.